sudo: required
services:
  - docker
dist: trusty
language: cpp
compiler:
  - clang
  - gcc
script:
  - "./configure --debug --devel --test && make && make test"
  - "./configure --test && make && make test"
