sudo: required
services:
  - docker
dist: xenial
language: cpp
compiler:
  - clang
  - gcc
script:
  - "./configure --debug --devel --test && ( [[ \"${CXX}\" == \"clang++\" ]] && scan-build --status-bugs -no-failure-reports make || make ) && make test"
  - "./configure --test && make && make test"
