version: "build-{build}"
build: Script

environment:
  matrix:
  - VS_VERSION: 14
    VS_PLATFORM: x64

branches:
  only:
    - master

skip_branch_with_pr: true

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive

before_build:
  - md build-debug
  - cd build-debug
  - cmake -G "Visual Studio %VS_VERSION%" -DDEBUG=1 -DSTATIC=1 -DCMAKE_VERBOSE_MAKEFILE=1 -DTESTS=1 ../
  - cd ../

build_script:
  - cd build-debug
  - cmake --build . --config Debug 
  - ctest . -C Debug --output-on-failure
  - cd ../

