version: "build-{build}"

environment:
  matrix:
  - VS_VERSION: 14
    VS_PLATFORM: win32
  - VS_VERSION: 14
    VS_PLATFORM: x64

branches:
  only:
    - master

skip_branch_with_pr: true

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive

before_build:
  - md build-release
  - cd build-release
  - cmake -G "Visual Studio %VS_VERSION%" -DSTATIC=1 -DCMAKE_VERBOSE_MAKEFILE=1 -DTESTS=1 ../
  - cd ../

build_script:
  - cd build-release
  - cmake --build . --config Release
  - ctest . -C Release --output-on-failure
  - cd ../

